version: '3'

services:
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8891:8888" # jupyter
    volumes:
      - "./notebook/:/home/jovyan/work"
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
